# trunk-ignore-all(prettier)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecodeals
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: ecodeals
  replicas: 3
  template:
    metadata:
      labels:
        app: ecodeals
    spec:
      containers:
      - name: ecodeals
        image: karthequian/helloworld:latest #${{ secrets.DOCKERHUB_USERNAME }}/ecodeals:${{ env.VERSION }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "1"
          limits:
            memory: "16Mi"
            cpu: "2"