apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecodeals
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: ecodeals
  replicas: 3
  template:
    metadata:
      labels:
        app: ecodeals
    spec:
      containers:
      - name: ecodeals
        image: ${{ secrets.DOCKERHUB_USERNAME }}/ecodeals:${{ env.VERSION }}
        ports:
        - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---

apiVersion: v1
kind: Service
metadata:
  name: ecodeals-service
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: ecodeals