apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048"
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 3
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
      - name: "2048"
        image: ${{ secrets.DOCKERHUB_USERNAME }}/2048:${{ env.VERSION }}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: "2048"