apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2048
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: test-2048
  replicas: 3
  template:
    metadata:
      labels:
        app: test-2048
    spec:
      containers:
      - name: test-2048
        image: kuza83/2048:test
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: test-2048