apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ${{ secrets.DOCKERHUB_USERNAME }}/2048:${{ env.VERSION }}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: app