apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: app-2048
  replicas: 3
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - name: app-2048
        image: ${{ secrets.DOCKERHUB_USERNAME }}/2048:${{ env.VERSION }}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: 2048-service
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: app-2048