apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-test
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: 2048-test
  replicas: 3
  template:
    metadata:
      labels:
        app: 2048-test
    spec:
      containers:
      - name: 2048-test
        image: kuza83/2048:test
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: 2048-service
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: 2048-test