# trunk-ignore-all(prettier)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  namespace: pre-prod
spec:
  selector:
    matchLabels:
      app: hw
  replicas: 3
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: ${{ secrets.DOCKERHUB_USERNAME }}/2048:${{ env.VERSION }}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: pre-prod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30023
  selector:
    app: app